name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  bun-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright
        run : npx playwright install chromium --with-deps

      - name: Run CI
        run: pnpm run ci --reporter=github

      - name: Run tests
        run: pnpm run test:ci

      # - name: Upload test snapshots
      #   uses: actions/upload-artifact@v4
      #   if: always()
      #   with:
      #     name: playwright-snapshots
      #     path: tests/**/*-snapshots/
